"""
Django settings for djangoProject_1 project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

#项目路径
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

#秘钥配置
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bew6iza5+zyi4e!b3crpay=j_)&_qz2sx^k$$8i(5kkze^cf7#'

#调试模式
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#域名访问权限
ALLOWED_HOSTS = []


# Application definition
#app列表
INSTALLED_APPS = [
    'django.contrib.admin', #后台管理
    'django.contrib.auth',  #用户认证
    'django.contrib.contenttypes',  #记录项目中的model元数据
    'django.contrib.sessions',  #表示用户身份，记录信息
    'django.contrib.messages',  #消息提示功能
    'django.contrib.staticfiles',   #寻找静态资源路径
    'HelloWorld.apps.HelloworldConfig',
]

MIDDLEWARE = [
    #内置的安全机制，保护用户与网站的通信安全
    'django.middleware.security.SecurityMiddleware',
    #会话Session功能
    'django.contrib.sessions.middleware.SessionMiddleware',
    #处理请求信息，规范化请求内容
    'django.middleware.common.CommonMiddleware',
    #开启CSRE防护功能
    'django.middleware.csrf.CsrfViewMiddleware',
    #开启内置的用户认证系统
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #开启内置的信息提示功能
    'django.contrib.messages.middleware.MessageMiddleware',
    #防止恶意程序单击劫持
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'HelloWorld.mymid.md1.Md1'
]

ROOT_URLCONF = 'djangoProject_1.urls'

TEMPLATES = [
    {
        #定义模板引擎，用于识别模板里面的变量和指令。内置的模板引擎有D]angoTemplates和jinja2.jinja2，
        # 每个模板引擎都有自己的变显和指令语法。
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #设置模板所在路径，告诉Django在哪个地方查找模板的位置，默认为空列表。
        'DIRS':[BASE_DIR/'templates',BASE_DIR/'HelloWorld/templates'],
        #是否在App里查找模板文件
        'APP_DIRS': True,
        #用于填充在RequestContext的上下文(模板里面的变量和指令)，一般情况下不做任何修改。
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject_1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tb_web_edu',
        'USER':'root',
        'PASSWORD':'123456',
        'HOST':'localhost',
        'PORT':'3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
#静态资源配置：只能访问应用下面的static文件夹
STATIC_URL = 'static/'

#设置静态资源文件集合
STATICFILES_DIRS =[BASE_DIR /"static",BASE_DIR /"HelloWorld/images"]

#设置媒体路由
MEDIA_URL = 'media/'
#共设置media目录的完整路径
MEDIA_ROOT= BASE_DIR/'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
